// File generated by FlutterFire CLI.
// Run `flutterfire configure` to regenerate this file with your Firebase project settings.
//
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    throw UnsupportedError(
      'DefaultFirebaseOptions have not been configured for this platform.',
    );
  }

  // TODO: Replace with your Firebase project values from `flutterfire configure`
  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyDXdCxJvi4UjWdFdCIF26qsAjd-VNZjJtQ",
      authDomain: "hoapp-db.firebaseapp.com",
      projectId: "hoapp-db",
      storageBucket: "hoapp-db.firebasestorage.app",
      messagingSenderId: "431525120566",
      appId: "1:431525120566:web:adbb03f24fd20310cbe697",
      measurementId: "G-8FSQWJN5KM");
}
