name: mobile
description: HOApp Mobile App for Residents
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  core_ui:
    path: ../../packages/core_ui
  core_domain:
    path: ../../packages/core_domain
  core_data:
    path: ../../packages/core_data
  provider: ^6.1.1
  app_links: ^6.3.3
  intl: ^0.19.0
  fl_chart: ^0.69.0
  table_calendar: ^3.1.2
  flutter_colorpicker: ^1.1.0
  file_picker: ^8.0.0
  supabase_flutter: ^2.5.3
  url_launcher: ^6.3.2
  mobile_scanner: ^7.2.0
  firebase_core: ^3.8.1
  firebase_messaging: ^15.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/flavors/elevehomes/

flutter_launcher_icons:
  ios: true
  android: true
  image_path: "assets/images/hoapp-icon.png"
  remove_alpha_ios: true
