// File generated by FlutterFire CLI.
// Run `flutterfire configure` to regenerate this file with your Firebase project settings.
//
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // TODO: Replace with your Firebase project values from `flutterfire configure`
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiwWiC8oC1UNvoezIFN3bpAMcSwPWedQo',
    appId: '1:431525120566:android:24f41d35970f519dcbe697',
    messagingSenderId: '431525120566',
    projectId: 'hoapp-db',
    storageBucket: 'hoapp-db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR-IOS-API-KEY',
    appId: 'YOUR-IOS-APP-ID',
    messagingSenderId: 'YOUR-SENDER-ID',
    projectId: 'YOUR-PROJECT-ID',
    storageBucket: 'YOUR-STORAGE-BUCKET',
    iosBundleId: 'com.hoapp.mobile',
  );

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyDXdCxJvi4UjWdFdCIF26qsAjd-VNZjJtQ",
      authDomain: "hoapp-db.firebaseapp.com",
      projectId: "hoapp-db",
      storageBucket: "hoapp-db.firebasestorage.app",
      messagingSenderId: "431525120566",
      appId: "1:431525120566:web:adbb03f24fd20310cbe697",
      measurementId: "G-8FSQWJN5KM");
}
